# Site settings
title: Jianwei Lyu
email: jianwei@arizona.edu
description: Academic webpage of Dr. Jianwei Lyu
baseurl: ""
url: ""

# Google analytics ID: Uncomment and your own, if you like
google_analytics: G-X5XP6GNW60
# google_analytics_4: XXX
# google_tag_manager: XXX

# Footer info
affiliation: >
  Jianwei Lyu<br/>
  Assistant Research Professor<br/>
  University of Arizona

location: >
  Steward Observatory 262<br/>
  933 N Cherry Ave<br/>
  Tucson, AZ 85719

contact: >
  <a href="mailto:jianwei@arizona.edu" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Jianwei via email</a> <br/>
  <a href="https://x.com/astroskii77"><i class="fa fa-twitter fa-1x"></i> Follow Jianwei on X/twitter</a> <br/>
  <a href="https://www.instagram.com/karlan777/"><i class="fa fa-instagram fa-1x"></i> Find Jianwei on Instagram</a>

# <a href="https://github.com/sbryngelson/academic-website-template"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: about
  - name: research
  - name: publications
#  - name: talks
  - name: download
#  - name: team
#  - name: teaching
  - name: notes
  - name: links
  - name: personal
#  - name: blogs

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

plugins: ["jekyll/scholar"]

scholar:
  last_name: Doe
  first_name: [John]

  style: annual-review-of-astronomy-and-astrophysics
  locale: en

  source: /assets/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
